version: "2.1"

volumes:
  state:

services:
  tailscale:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: on-failure
    volumes:
      - state:/var/lib/tailscale
    environment:
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      - TS_AUTH_ONCE=true
      - TS_STATE_DIR=/var/lib/tailscale
      - "TS_EXTRA_ARGS=--accept-routes --advertise-exit-node"
      - TS_USERSPACE=false
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/

  glances:
    image: nicolargo/glances:3.4.0.5
    restart: always
    pid: host
    environment:
      - TZ=Europe/Stockholm
      - "GLANCES_OPT=-w -C /data/infra/glances/glances.conf" # Webserver mode
    labels:
      - io.balena.features.balena-socket=1
    ports:
      - 80:61208
